# Generated by Django 3.0.3 on 2020-04-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_auto_20200421_1627'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users_in_course',
            field=models.ManyToManyField(related_name='courses_enrolled_in', to='login_reg.User', verbose_name='users_who_enrolled_in_this_course'),
        ),
    ]
